### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by leaanthony** [tadvi/winc#7]
Hi. Just wondering what the status is of this project as there hasn't been any activity for a while. Thanks.

**Comment by tadvi** [comment]
Pull requests welcome. I do not time to work on this project.

**Comment by leaanthony** [comment]
Thanks for replying. Rather than take up your time talking about what you'd like in terms of PRs then sending you a whole load of PRs to review, I'm going to just keep pushing changes to [my fork](https://github.com/leaanthony/winc/) and you are welcome to browse/pull what you like. If you need my help with that then feel free to ask.

Updates so far:
* Support SubMenus in MenuItems
* Support Radio Groups in MenuItems
* Support min/max window size, DPI aware
* Support Maximise, Minimise and restore window
* Support Fullscreen /UnFullScreen
* Made both SetPos and Center multi-monitor aware
* Fixed typo in `procEndPaint`
* Added `SetTranslucentBackground` for making the window background blurry (sort-of acrylic effect)

It's a little confusing what should be in a Form and what should be in the ControlBase so if you have any suggestions.... :-) . Thanks for the amazing project!

**Comment by tadvi** [comment]
Let me know when fork is ready to merge, I will review and accept then.

**Comment by ooing** [comment]
how to set   btn  color
